---
- name: Setup webserver
  hosts: all
  become: true
  tasks:
    - name: Deploy SSH keys
      ansible.builtin.import_role:
        name: ssh
      tags: ssh

    - name: Basic server setup
      ansible.builtin.import_role:
        name: base
      tags: base
